# Generated by Django 5.2.7 on 2025-10-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_login', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_crear_automovil', 'Puede ingresar un nuevo automovil'), ('view_editar_automovil', 'Puede editar un automovil'), ('view_eliminar_automovil', 'Puede eliminar un automovil'), ('view_ver_detalle_automovil', 'Puede ver el detalle de un automovil'), ('view_listar_automoviles', 'Puede ver la lista de automoviles'), ('view_concesionario', 'Puede ver la concesionaria'), ('view_inventario', 'Puede ver el inventario'), ('view_agregar_al_inventario', 'Puede agregar al inventario'), ('view_modificar_inventario', 'Puede modificar el inventario'), ('view_eliminar_del_inventario', 'Puede eliminar del inventario'), ('view_gestionar_usuarios', 'Puede gestionar usuarios'), ('view_login', 'Puede ingresar al sistema'), ('view_logout', 'Puede salir del sistema'), ('view_automovil', 'Puede ver un automovil'), ('view_automoviles', 'Puede ver la lista de automoviles')]},
        ),
    ]
