# Generated by Django 5.2.7 on 2025-10-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_login', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': []},
        ),
    ]
