# Generated by Django 5.2.7 on 2025-10-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_login', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('InventarioView', 'Permiso para ver el inventario')]},
        ),
    ]
