# Generated by Django 5.2.6 on 2025-10-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_login', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': []},
        ),
    ]
