# Generated by Django 5.2.7 on 2025-10-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_login', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('InventarioView', 'Permiso para ver el inventario'), ('VentasView', 'Permiso para ver ventas'), ('ReportesView', 'Permiso para ver reportes'), ('ConfiguracionView', 'Permiso para configurar el sistema')]},
        ),
    ]
