# Generated by Django 5.2.7 on 2025-10-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_conces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos/'),
        ),
    ]
