# Generated by Django 5.2.6 on 2025-10-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_conces', '0002_automovil_descripcion_automovil_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'permissions': [('change_auto', 'Puede modificar automóviles'), ('delete_auto', 'Puede eliminar automóviles'), ('view_inventario', 'Puede ver el inventario completo'), ('manage_precio', 'Puede gestionar precios de automóviles')]},
        ),
    ]
