# Generated by Django 5.2.7 on 2025-10-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_conces', '0003_alter_automovil_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'permissions': [('add_auto', 'Puede agregar automóviles'), ('change_auto', 'Puede modificar automóviles'), ('delete_auto', 'Puede eliminar automóviles'), ('view_inventario', 'Puede ver el inventario completo'), ('manage_precio', 'Puede gestionar precios de automóviles')]},
        ),
    ]
